[book]
authors = ["Franco Barreneche", "Gianluca Belinche", "Guido Botta", "Julian Ventura"]
language = "en"
multilingual = false
src = "src"
title = "Agni B3V"
[output.html]
mathjax-support = true
default-theme = "rust"
preferred-dark-theme = "rust"
